import { Link, useParams } from 'react-router-dom'
import { EmptyState } from '../components/ui/states'
import { ClientLoginForm, RegisterForm, StaffLoginForm } from '../features/auth/auth-forms'
import { PageContainer } from '../components/layout/page-container'
import { SectionHeading } from '../components/ui/section-heading'
import { ServiceCard } from '../components/ui/service-card'

export function HomePage() { return <>
  <section className="hero"><PageContainer className="hero-grid"><div className="hero-copy"><span className="eyebrow">Atención simple, seguimiento claro</span><h1>Orientación que continúa contigo.</h1><p className="lead">Encuentra información, conversa con el asistente del prototipo y, cuando una consulta lo requiera, continúa su seguimiento mediante un ticket.</p><div className="hero-actions"><Link className="button button-large" to="/chat">Conversar con el asistente <span aria-hidden="true">→</span></Link><Link className="button button-secondary button-large" to="/login">Consultar mis tickets</Link></div><p className="hero-note"><span aria-hidden="true">●</span> Servicio exclusivamente demostrativo. No procesa operaciones bancarias.</p></div><div className="hero-visual" aria-label="Vista conceptual del flujo de atención"><div className="visual-glow" /><div className="assistant-card"><span className="assistant-label">Asistente del prototipo</span><p>¿En qué tema necesitas orientación?</p><div className="assistant-options"><span>Tarjetas</span><span>Cuentas</span><span>Créditos</span></div></div><div className="ticket-preview"><span className="ticket-dot" /><div><small>Seguimiento demo</small><strong>Consulta recibida</strong></div><span className="status-pill">En revisión</span></div></div></PageContainer></section>
  <section className="home-section services-section" id="servicios"><PageContainer><SectionHeading eyebrow="Información organizada" title="¿Sobre qué deseas consultar?" align="center">Explora orientación general. Las respuestas no sustituyen los canales oficiales ni realizan operaciones.</SectionHeading><div className="services-grid"><ServiceCard icon="▣" title="Tarjetas">Requisitos generales, uso responsable y preguntas frecuentes informativas.</ServiceCard><ServiceCard icon="◫" title="Cuentas">Orientación sobre tipos de cuenta y documentación referencial.</ServiceCard><ServiceCard icon="↗" title="Créditos">Información general sobre alternativas y etapas de evaluación.</ServiceCard><ServiceCard icon="⌁" title="Banca digital">Ayuda educativa sobre canales y buenas prácticas de seguridad.</ServiceCard></div></PageContainer></section>
  <section className="home-section process-section" id="proceso"><PageContainer><SectionHeading eyebrow="Un recorrido transparente" title="De la consulta al seguimiento">Cada etapa indica qué ocurre con tu solicitud dentro de este entorno académico.</SectionHeading><ol className="process-grid"><li><span>01</span><div><h3>Consulta</h3><p>Describe tu duda sin compartir datos bancarios reales.</p></div></li><li><span>02</span><div><h3>Respuesta</h3><p>Recibe orientación basada en información del prototipo.</p></div></li><li><span>03</span><div><h3>Ticket</h3><p>Si el caso requiere continuidad, se prepara una solicitud.</p></div></li><li><span>04</span><div><h3>Seguimiento</h3><p>Consulta el estado y las actualizaciones desde tu portal.</p></div></li></ol></PageContainer></section>
  <section className="home-section faq-preview" id="preguntas"><PageContainer><div className="split-heading"><SectionHeading eyebrow="Respuestas rápidas" title="Preguntas frecuentes">Algunas aclaraciones sobre el alcance de esta experiencia.</SectionHeading><Link className="text-link" to="/preguntas-frecuentes">Ver todas las preguntas <span aria-hidden="true">→</span></Link></div><div className="faq-grid"><article><h3>¿Puedo realizar operaciones bancarias?</h3><p>No. Esta plataforma solo demuestra orientación y gestión de tickets.</p></article><article><h3>¿Debo usar mis datos reales?</h3><p>No. Utiliza únicamente datos y cuentas ficticias de demostración.</p></article><article><h3>¿Cómo consulto una solicitud?</h3><p>Ingresa al portal de clientes demo para ver el seguimiento disponible.</p></article></div></PageContainer></section>
  <section className="home-section channels-section" id="canales"><PageContainer className="channels-grid"><div><SectionHeading eyebrow="Canales simulados" title="Elige cómo orientarte">Estos canales representan posibles puntos de atención y no conectan con servicios bancarios reales.</SectionHeading><Link className="button button-light" to="/chat">Abrir orientación virtual</Link></div><div className="channel-list"><article><span aria-hidden="true">01</span><div><h3>Asistente virtual</h3><p>Disponible dentro del prototipo para consultas informativas.</p></div><small>Simulado</small></article><article><span aria-hidden="true">02</span><div><h3>Centro de preguntas</h3><p>Respuestas organizadas por temas frecuentes.</p></div><small>Informativo</small></article><article><span aria-hidden="true">03</span><div><h3>Portal de seguimiento</h3><p>Consulta solicitudes asociadas a tu cuenta demo.</p></div><small>Demostración</small></article></div></PageContainer></section>
  <section className="home-cta"><PageContainer><div><span className="eyebrow">Comienza por una consulta</span><h2>Una experiencia de atención diseñada para orientarte.</h2></div><Link className="button button-large" to="/chat">Conversar ahora <span aria-hidden="true">→</span></Link></PageContainer></section>
  </> }
export function LoginPage() { return <div className="auth-page"><PageContainer><ClientLoginForm /></PageContainer></div> }
export function StaffLoginPage() { return <div className="auth-page staff-auth-page"><PageContainer><StaffLoginForm /></PageContainer></div> }
export function RegisterPage() { return <div className="auth-page"><PageContainer><RegisterForm /></PageContainer></div> }
export function ClientHomePage() { return <section><div className="eyebrow">Portal del cliente</div><h1>Tu espacio de atención</h1><p className="lead">Aquí encontrarás el resumen de tus solicitudes cuando la sesión esté conectada.</p><div className="stat-grid"><div className="card"><span>Tickets abiertos</span><strong>—</strong></div><div className="card"><span>Última actualización</span><strong>—</strong></div></div><Link className="button" to="/cliente/tickets">Consultar mis tickets</Link></section> }
export function ClientTicketsPage() { return <section><div className="eyebrow">Portal del cliente</div><h1>Mis tickets</h1><p className="lead">Lista preparada para <code>GET /tickets/mine</code>.</p><EmptyState title="Sin tickets para mostrar" message="Conecta la API para visualizar tus solicitudes." /></section> }
export function TicketDetailPage() { const { ticketId } = useParams(); return <section><Link className="back-link" to="/cliente/tickets">← Volver a mis tickets</Link><div className="eyebrow">Detalle del ticket</div><h1>Solicitud {ticketId}</h1><EmptyState title="Detalle pendiente de conexión" message="El historial y comentarios se cargarán desde la API." /></section> }
export function PanelHomePage() { return <section><div className="eyebrow">Operaciones</div><h1>Panel interno</h1><p className="lead">Vista base para asesores y supervisores. Los indicadores se conectarán a reportes reales.</p><div className="stat-grid"><div className="card"><span>Nuevos</span><strong>—</strong></div><div className="card"><span>En proceso</span><strong>—</strong></div><div className="card"><span>Resueltos</span><strong>—</strong></div></div></section> }
export function PanelTicketsPage() { return <section><div className="eyebrow">Operaciones</div><h1>Bandeja de tickets</h1><p className="lead">Vista preparada para <code>GET /tickets</code>.</p><EmptyState title="Bandeja vacía" message="Los tickets permitidos aparecerán al conectar la API." /></section> }
export function PanelTicketDetailPage() { const { ticketId } = useParams(); return <section><Link className="back-link" to="/personal/tickets">← Volver a la bandeja</Link><div className="eyebrow">Gestión interna</div><h1>Ticket {ticketId}</h1><EmptyState title="Detalle pendiente de conexión" message="Las acciones de clasificación, asignación y estado dependen del backend." /></section> }
export function KnowledgePage() { return <section><div className="eyebrow">Administración</div><h1>Base de conocimiento</h1><p className="lead">Vista preparada para la gestión de FAQ y categorías según los roles permitidos.</p><EmptyState title="Sin artículos cargados" message="El contenido se administrará mediante los endpoints documentados." /></section> }
export function NotFoundPage() { return <PageContainer as="section" className="not-found standard-page"><div className="eyebrow">Error 404</div><h1>Página no encontrada</h1><p className="lead">La dirección que buscas no existe en este prototipo.</p><Link className="button" to="/">Volver al inicio</Link></PageContainer> }
