import { Link, useParams } from 'react-router-dom'
import { EmptyState } from '../components/ui/states'

export function HomePage() { return <section className="hero"><div className="eyebrow">Orientación clara para cada consulta</div><h1>Resuelve tus consultas con confianza.</h1><p className="lead">Un punto de partida académico para conversar, encontrar respuestas y dar seguimiento a solicitudes de atención.</p><div className="hero-actions"><Link className="button" to="/chat">Abrir asistente</Link><Link className="button button-secondary" to="/preguntas-frecuentes">Ver preguntas frecuentes</Link></div><div className="feature-grid"><article className="card"><span className="icon">01</span><h2>Pregunta</h2><p>Explora respuestas organizadas en un espacio sencillo.</p></article><article className="card"><span className="icon">02</span><h2>Conversa</h2><p>Usa el asistente virtual del prototipo para orientarte.</p></article><article className="card"><span className="icon">03</span><h2>Da seguimiento</h2><p>La futura experiencia de tickets reunirá tu historial.</p></article></div></section> }
export function LoginPage() { return <section className="auth-card card"><div className="eyebrow">Acceso al prototipo</div><h1>Inicia sesión</h1><p>La autenticación real se habilitará en una siguiente fase.</p><form><label htmlFor="email">Correo electrónico</label><input id="email" type="email" placeholder="tu@correo.com" /><label htmlFor="password">Contraseña</label><input id="password" type="password" placeholder="••••••••" /><button className="button" type="button" disabled>Iniciar sesión próximamente</button></form><p className="helper">¿Aún no tienes cuenta? <Link to="/registro">Regístrate</Link></p></section> }
export function RegisterPage() { return <section className="auth-card card"><div className="eyebrow">Nueva cuenta de cliente</div><h1>Regístrate</h1><p>El formulario de registro se conectará con el endpoint documentado en la siguiente fase.</p><form><label htmlFor="name">Nombre completo</label><input id="name" placeholder="Tu nombre" /><label htmlFor="register-email">Correo electrónico</label><input id="register-email" type="email" placeholder="tu@correo.com" /><button className="button" type="button" disabled>Registro próximamente</button></form><p className="helper"><Link to="/login">Volver a iniciar sesión</Link></p></section> }
export function FaqPage() { return <section><div className="eyebrow">Centro de ayuda</div><h1>Preguntas frecuentes</h1><p className="lead">Esta vista está preparada para consumir las FAQ activas de <code>GET /faqs</code>.</p><EmptyState title="Contenido pendiente de conexión" message="Las respuestas se mostrarán cuando el backend esté disponible." /></section> }
export function ChatPage() { return <section><div className="eyebrow">Asistente virtual del prototipo</div><h1>Conversación de orientación</h1><div className="chat-card card"><div className="chat-message bot"><strong>Asistente</strong><p>Hola. Esta base visual está lista para conectar conversaciones documentadas por la API.</p></div><div className="chat-message user"><strong>Tu consulta</strong><p>Las respuestas reales se habilitarán en la siguiente fase.</p></div><div className="chat-composer"><input aria-label="Escribe tu consulta" placeholder="Escribe tu consulta…" disabled /><button className="button" disabled>Enviar</button></div></div></section> }
export function ClientHomePage() { return <section><div className="eyebrow">Portal del cliente</div><h1>Tu espacio de atención</h1><p className="lead">Aquí encontrarás el resumen de tus solicitudes cuando la sesión esté conectada.</p><div className="stat-grid"><div className="card"><span>Tickets abiertos</span><strong>—</strong></div><div className="card"><span>Última actualización</span><strong>—</strong></div></div><Link className="button" to="/cliente/tickets">Consultar mis tickets</Link></section> }
export function ClientTicketsPage() { return <section><div className="eyebrow">Portal del cliente</div><h1>Mis tickets</h1><p className="lead">Lista preparada para <code>GET /tickets/mine</code>.</p><EmptyState title="Sin tickets para mostrar" message="Conecta la API para visualizar tus solicitudes." /></section> }
export function TicketDetailPage() { const { ticketId } = useParams(); return <section><Link className="back-link" to="/cliente/tickets">← Volver a mis tickets</Link><div className="eyebrow">Detalle del ticket</div><h1>Solicitud {ticketId}</h1><EmptyState title="Detalle pendiente de conexión" message="El historial y comentarios se cargarán desde la API." /></section> }
export function PanelHomePage() { return <section><div className="eyebrow">Operaciones</div><h1>Panel interno</h1><p className="lead">Vista base para asesores y supervisores. Los indicadores se conectarán a reportes reales.</p><div className="stat-grid"><div className="card"><span>Nuevos</span><strong>—</strong></div><div className="card"><span>En proceso</span><strong>—</strong></div><div className="card"><span>Resueltos</span><strong>—</strong></div></div></section> }
export function PanelTicketsPage() { return <section><div className="eyebrow">Operaciones</div><h1>Bandeja de tickets</h1><p className="lead">Vista preparada para <code>GET /tickets</code>.</p><EmptyState title="Bandeja vacía" message="Los tickets permitidos aparecerán al conectar la API." /></section> }
export function PanelTicketDetailPage() { const { ticketId } = useParams(); return <section><Link className="back-link" to="/panel/tickets">← Volver a la bandeja</Link><div className="eyebrow">Gestión interna</div><h1>Ticket {ticketId}</h1><EmptyState title="Detalle pendiente de conexión" message="Las acciones de clasificación, asignación y estado dependen del backend." /></section> }
export function KnowledgePage() { return <section><div className="eyebrow">Administración</div><h1>Base de conocimiento</h1><p className="lead">Vista preparada para la gestión de FAQ y categorías según los roles permitidos.</p><EmptyState title="Sin artículos cargados" message="El contenido se administrará mediante los endpoints documentados." /></section> }
export function NotFoundPage() { return <section className="not-found"><div className="eyebrow">404</div><h1>Página no encontrada</h1><p className="lead">La dirección que buscas no existe en este prototipo.</p><Link className="button" to="/">Volver al inicio</Link></section> }
