import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { ApiError } from '../../lib/api-client'
import type { LoginRequest, RegisterRequest } from '../../types/auth'
import { useAuth } from './auth-provider'
import { register } from './auth-service'

const passwordRule = z.string().min(8, 'La contraseña debe cumplir las reglas.').max(128, 'La contraseña debe cumplir las reglas.').regex(/[A-Z]/, 'La contraseña debe cumplir las reglas.').regex(/[a-z]/, 'La contraseña debe cumplir las reglas.').regex(/[0-9]/, 'La contraseña debe cumplir las reglas.')
const loginSchema = z.object({ email: z.string().trim().email('Ingresa un correo válido.'), password: z.string().min(1, 'La contraseña es obligatoria.') })
const registerSchema = z.object({ full_name: z.string().trim().min(1, 'El nombre completo es obligatorio.'), email: z.string().trim().email('Ingresa un correo válido.'), phone: z.string().optional(), password: passwordRule, confirmPassword: z.string().min(1, 'Confirma tu contraseña.') }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'Las contraseñas no coinciden.' })
const errorMessage = (error: unknown, conflict: string): string => error instanceof ApiError && error.status === 409 ? conflict : error instanceof ApiError && error.status === 422 ? 'Revisa los datos ingresados.' : 'No fue posible completar la solicitud. Inténtalo nuevamente.'

export function LoginForm() { const { signIn } = useAuth(); const navigate = useNavigate(); const [serverError, setServerError] = useState<string | null>(null); const { register: field, handleSubmit, formState: { errors, isSubmitting } } = useForm<LoginRequest>({ resolver: zodResolver(loginSchema) }); const submit = async (data: LoginRequest) => { setServerError(null); try { const session = await signIn(data); navigate(session.user.role === 'CLIENTE' ? '/cliente' : session.user.role === 'ASESOR' ? '/panel/tickets' : '/panel', { replace: true }) } catch (error: unknown) { setServerError(error instanceof ApiError && error.status === 401 ? 'El correo o la contraseña son incorrectos.' : errorMessage(error, 'No fue posible iniciar sesión.') ) } }; return <section className="auth-card card"><div className="eyebrow">Acceso al prototipo</div><h1>Inicia sesión</h1><p>Usa una cuenta ficticia del entorno académico.</p>{serverError && <div className="form-error" role="alert">{serverError}</div>}<form onSubmit={handleSubmit(submit)} noValidate><label htmlFor="login-email">Correo electrónico</label><input id="login-email" type="email" autoComplete="email" {...field('email')} />{errors.email && <span className="field-error">{errors.email.message}</span>}<label htmlFor="login-password">Contraseña</label><input id="login-password" type="password" autoComplete="current-password" {...field('password')} />{errors.password && <span className="field-error">{errors.password.message}</span>}<button className="button" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Validando…' : 'Iniciar sesión'}</button></form><p className="helper">¿Aún no tienes cuenta? <Link to="/registro">Regístrate</Link></p></section> }

export function RegisterForm() { const navigate = useNavigate(); const [serverError, setServerError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const { register: field, handleSubmit, formState: { errors, isSubmitting } } = useForm<RegisterRequest & { confirmPassword: string }>({ resolver: zodResolver(registerSchema) }); const submit = async (data: RegisterRequest & { confirmPassword: string }) => { setServerError(null); try { const payload: RegisterRequest = { full_name: data.full_name, email: data.email, phone: data.phone, password: data.password }; await register(payload); setSuccess(true); setTimeout(() => navigate('/login'), 700) } catch (error: unknown) { setServerError(errorMessage(error, 'Ese correo ya está registrado.')) } }; return <section className="auth-card card"><div className="eyebrow">Nueva cuenta de cliente</div><h1>Regístrate</h1><p>Cuenta ficticia para el prototipo académico.</p>{success && <div className="form-success" role="status">Cuenta creada. Redirigiendo al inicio de sesión…</div>}{serverError && <div className="form-error" role="alert">{serverError}</div>}<form onSubmit={handleSubmit(submit)} noValidate><label htmlFor="register-name">Nombre completo</label><input id="register-name" autoComplete="name" {...field('full_name')} />{errors.full_name && <span className="field-error">{errors.full_name.message}</span>}<label htmlFor="register-email">Correo electrónico</label><input id="register-email" type="email" autoComplete="email" {...field('email')} />{errors.email && <span className="field-error">{errors.email.message}</span>}<label htmlFor="register-phone">Teléfono <span className="optional">(opcional)</span></label><input id="register-phone" type="tel" autoComplete="tel" {...field('phone')} /><label htmlFor="register-password">Contraseña</label><input id="register-password" type="password" autoComplete="new-password" {...field('password')} /><ul className="password-rules"><li>Mínimo 8 caracteres y máximo 128</li><li>Al menos una mayúscula, una minúscula y un número</li></ul>{errors.password && <span className="field-error">{errors.password.message}</span>}<label htmlFor="confirm-password">Confirmar contraseña</label><input id="confirm-password" type="password" autoComplete="new-password" {...field('confirmPassword')} />{errors.confirmPassword && <span className="field-error">{errors.confirmPassword.message}</span>}<button className="button" type="submit" disabled={isSubmitting}>{isSubmitting ? 'Creando cuenta…' : 'Crear cuenta'}</button></form><p className="helper"><Link to="/login">Volver a iniciar sesión</Link></p></section> }
